
import { Item } from './types';

export const ItemsList: Item[] = [
  {
    "id": 0,
    "name": "Basic Magazine",
    "tier": "T1",
    "type": "Bullet",
    "bulletPower": 0.21,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.24,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 1,
    "name": "Close Quarters",
    "tier": "T1",
    "type": "Bullet",
    "bulletPower": 0.31,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 85,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 2,
    "name": "Headshot Booster",
    "tier": "T1",
    "type": "Bullet",
    "bulletPower": 0.06,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.05,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 40,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 3,
    "name": "High-Velocity Mag",
    "tier": "T1",
    "type": "Bullet",
    "bulletPower": 0.2,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 50,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 4,
    "name": "Hollow Point Ward",
    "tier": "T1",
    "type": "Bullet",
    "bulletPower": 0.26,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 4,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 85,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 5,
    "name": "Monster Rounds",
    "tier": "T1",
    "type": "Bullet",
    "bulletPower": 0.06,
    "vitality": 0,
    "bonusHealth": 50,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 1,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 6,
    "name": "Rapid Rounds",
    "tier": "T1",
    "type": "Bullet",
    "bulletPower": 0.06,
    "vitality": 0,
    "bonusHealth": -50,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.12,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 1,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 7,
    "name": "Restorative Shot",
    "tier": "T1",
    "type": "Bullet",
    "bulletPower": 0.14,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.07,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 8,
    "name": "Active Reload",
    "tier": "T2",
    "type": "Bullet",
    "bulletPower": 0.2,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.2,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0.22,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 9,
    "name": "Berserker",
    "tier": "T2",
    "type": "Bullet",
    "bulletPower": 0.1,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.08,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 10,
    "name": "Kinetic Dash",
    "tier": "T2",
    "type": "Bullet",
    "bulletPower": 0.1,
    "vitality": 0,
    "bonusHealth": 100,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.25,
    "meleeDamage": 0,
    "healthRegen": 1.5,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 11,
    "name": "Long Range",
    "tier": "T2",
    "type": "Bullet",
    "bulletPower": 0.5,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.2,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 90,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 12,
    "name": "Melee Charge",
    "tier": "T2",
    "type": "Bullet",
    "bulletPower": 0.25,
    "vitality": 0,
    "bonusHealth": 100,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 1,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 13,
    "name": "Mystic Shot",
    "tier": "T2",
    "type": "Bullet",
    "bulletPower": 0.22,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 4,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 14,
    "name": "Slowing Bullets",
    "tier": "T2",
    "type": "Bullet",
    "bulletPower": 0.26,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 5,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 15,
    "name": "Soul Shredder Bullets",
    "tier": "T2",
    "type": "Bullet",
    "bulletPower": 0.16,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0.2,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 16,
    "name": "Swift Striker",
    "tier": "T2",
    "type": "Bullet",
    "bulletPower": 0.1,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.1,
    "fireRate": 0.22,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": -0.05,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 17,
    "name": "Fleetfoot",
    "tier": "T2",
    "type": "Bullet",
    "bulletPower": 0.1,
    "vitality": 0,
    "bonusHealth": 75,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.3,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 4,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "Yes"
  },
  {
    "id": 18,
    "name": "Burst Fire",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.14,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.12,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 19,
    "name": "Escalating Resilience",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.28,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.14,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 20,
    "name": "Headhunter",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.29000000000000004,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 150,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 2,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 21,
    "name": "Hunter's Aura",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.14,
    "vitality": 0,
    "bonusHealth": 150,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": -0.1,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 22,
    "name": "Intensifying Magazine",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.34,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.25,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 23,
    "name": "Point Blank",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.5900000000000001,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.15,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 24,
    "name": "Pristine Emblem",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.39,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.12,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 25,
    "name": "Sharpshooter",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.84,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.2,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 175,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 26,
    "name": "Tesla Bullets",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.14,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.14,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 27,
    "name": "Titanic Magazine",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.32,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 1,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.15,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 28,
    "name": "Toxic Bullets",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.14,
    "vitality": 0,
    "bonusHealth": 100,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 29,
    "name": "Alchemical Fire",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.28,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 7,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 225,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 30,
    "name": "Heroic Aura",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.14,
    "vitality": 0,
    "bonusHealth": 150,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0.2,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 1,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "Yes"
  },
  {
    "id": 31,
    "name": "Warp Stone",
    "tier": "T3",
    "type": "Bullet",
    "bulletPower": 0.34,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 8,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.3,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 32,
    "name": "Crippling Headshot",
    "tier": "T4",
    "type": "Bullet",
    "bulletPower": 0.38,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0.1,
    "spiritLifesteal": 0.1,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0.24,
    "spiritResistReduction": 0.24,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 33,
    "name": "Frenzy",
    "tier": "T4",
    "type": "Bullet",
    "bulletPower": 0.48,
    "vitality": 0,
    "bonusHealth": 300,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.4,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.45,
    "movementSpeed": 4,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 34,
    "name": "Glass Cannon",
    "tier": "T4",
    "type": "Bullet",
    "bulletPower": 0.8799999999999999,
    "vitality": 0,
    "bonusHealth": -0.15,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.1,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 1,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 35,
    "name": "Lucky Shot",
    "tier": "T4",
    "type": "Bullet",
    "bulletPower": 0.18,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.3,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 36,
    "name": "Ricochet",
    "tier": "T4",
    "type": "Bullet",
    "bulletPower": 0.18,
    "vitality": 0,
    "bonusHealth": 150,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.35,
    "fireRate": 0.12,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 37,
    "name": "Sipon Bullets",
    "tier": "T4",
    "type": "Bullet",
    "bulletPower": 0.46,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 38,
    "name": "Spiritual Overflow",
    "tier": "T4",
    "type": "Bullet",
    "bulletPower": 0.18,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.2,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0.1,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 39,
    "name": "Silencer",
    "tier": "T4",
    "type": "Bullet",
    "bulletPower": 0.32999999999999996,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 40,
    "name": "Vampiric Burst",
    "tier": "T4",
    "type": "Bullet",
    "bulletPower": 0.43,
    "vitality": 0,
    "bonusHealth": 150,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.5,
    "fireRate": 0.4,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 1,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 2,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 41,
    "name": "Enduring Spirit",
    "tier": "T1",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.11,
    "bonusHealth": 75,
    "spiritPower": 4,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0.08,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 42,
    "name": "Extra Health",
    "tier": "T1",
    "type": "Vitality",
    "bulletPower": 0.05,
    "vitality": 0.11,
    "bonusHealth": 160,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 43,
    "name": "Extra Regen",
    "tier": "T1",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.11,
    "bonusHealth": 25,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.08,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 2.8,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 44,
    "name": "Extra Stamina",
    "tier": "T1",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.11,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.07,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 45,
    "name": "Melee Lifesteal",
    "tier": "T1",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.11,
    "bonusHealth": 75,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0.15,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 46,
    "name": "Sprint Boots",
    "tier": "T1",
    "type": "Vitality",
    "bulletPower": 0.04,
    "vitality": 0.11,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 1,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 2,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 47,
    "name": "Healing Rite",
    "tier": "T1",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.11,
    "bonusHealth": 45,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 48,
    "name": "Bullet Armor",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0.06,
    "vitality": 0.14,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.2,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 49,
    "name": "Bullet Lifesteal",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.14,
    "bonusHealth": 75,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0.28,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 50,
    "name": "Combat Barrier",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0.28,
    "vitality": 0.14,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.08,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 300,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 51,
    "name": "Debuff Reducer",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0.06,
    "vitality": 0.14,
    "bonusHealth": 75,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 52,
    "name": "Enchanter's Barrier",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.14,
    "bonusHealth": 0,
    "spiritPower": 20,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 300,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 53,
    "name": "Enduring Speed",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.14,
    "bonusHealth": 75,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 1.5,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 1.4,
    "sprintSpeed": 2,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 54,
    "name": "Healbane",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.14,
    "bonusHealth": 75,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 55,
    "name": "Healing Booster",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.14,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 2,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.06,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 56,
    "name": "Reactive Barrier",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.14,
    "bonusHealth": 75,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.15,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 2,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 400,
    "spiritShieldHealth": 200,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 57,
    "name": "Sprit Armor",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.14,
    "bonusHealth": 0,
    "spiritPower": 5,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.2,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 58,
    "name": "Sprit Lifesteal",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.14,
    "bonusHealth": 75,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0.23,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 59,
    "name": "Divine Barrier",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.14,
    "bonusHealth": 75,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 300,
    "spiritShieldHealth": 300,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 2,
    "sprintSpeed": 1,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 60,
    "name": "Health Nova",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0.1,
    "vitality": 0.14,
    "bonusHealth": 100,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 61,
    "name": "Restorative Locket",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.14,
    "bonusHealth": 0,
    "spiritPower": 5,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.08,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "Yes"
  },
  {
    "id": 62,
    "name": "Return Fire",
    "tier": "T2",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.14,
    "bonusHealth": 125,
    "spiritPower": 7,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.07,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 63,
    "name": "Fortitude",
    "tier": "T3",
    "type": "Vitality",
    "bulletPower": 0.25,
    "vitality": 0.17,
    "bonusHealth": 275,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 2,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 64,
    "name": "Improved Bullet Armor",
    "tier": "T3",
    "type": "Vitality",
    "bulletPower": 0.1,
    "vitality": 0.17,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.45,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 65,
    "name": "Improved Sprit Armor",
    "tier": "T3",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.17,
    "bonusHealth": 0,
    "spiritPower": 8,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.45,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 66,
    "name": "Lifestrike",
    "tier": "T3",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.17,
    "bonusHealth": 125,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0.4,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.08,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 67,
    "name": "Superior Stamina",
    "tier": "T3",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.17,
    "bonusHealth": 0,
    "spiritPower": 8,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.07,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 68,
    "name": "Veil Walker",
    "tier": "T3",
    "type": "Vitality",
    "bulletPower": 0.1,
    "vitality": 0.17,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0.12,
    "fireRate": 0.3,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 200,
    "spiritShieldHealth": 200,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 3,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 69,
    "name": "Debuff Remover",
    "tier": "T3",
    "type": "Vitality",
    "bulletPower": 0.2,
    "vitality": 0.17,
    "bonusHealth": 125,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 3,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "Yes"
  },
  {
    "id": 70,
    "name": "Majestic Leap",
    "tier": "T3",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.17,
    "bonusHealth": 125,
    "spiritPower": 10,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 71,
    "name": "Metal Skin",
    "tier": "T3",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.17,
    "bonusHealth": 125,
    "spiritPower": 8,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.08,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 72,
    "name": "Rescue Beam",
    "tier": "T3",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.17,
    "bonusHealth": 125,
    "spiritPower": 9,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 2,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 73,
    "name": "Inhibitor",
    "tier": "T4",
    "type": "Vitality",
    "bulletPower": 0.25,
    "vitality": 0.2,
    "bonusHealth": 175,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 74,
    "name": "Leech",
    "tier": "T4",
    "type": "Vitality",
    "bulletPower": 0.15,
    "vitality": 0.2,
    "bonusHealth": 175,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0.35,
    "spiritLifesteal": 0.35,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 75,
    "name": "Soul Rebirth",
    "tier": "T4",
    "type": "Vitality",
    "bulletPower": 0.2,
    "vitality": 0.2,
    "bonusHealth": 0,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 76,
    "name": "Colossus",
    "tier": "T4",
    "type": "Vitality",
    "bulletPower": 0.2,
    "vitality": 0.2,
    "bonusHealth": 600,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0.2,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.4,
    "spiritResist": 0.4,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 77,
    "name": "Phantom Strike",
    "tier": "T4",
    "type": "Vitality",
    "bulletPower": 0.3,
    "vitality": 0.2,
    "bonusHealth": 0,
    "spiritPower": 0,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.15,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 78,
    "name": "Shadow Weave",
    "tier": "T4",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.2,
    "bonusHealth": 0,
    "spiritPower": 55,
    "ammoFlat": 0,
    "ammoPercentage": 0.3,
    "fireRate": 0.4,
    "meleeDamage": 0,
    "healthRegen": 15,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 300,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 2,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 79,
    "name": "Unstoppable",
    "tier": "T4",
    "type": "Vitality",
    "bulletPower": 0,
    "vitality": 0.2,
    "bonusHealth": 150,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.15,
    "movementSpeed": 1,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 80,
    "name": "Ammo Scavenger",
    "tier": "T1",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 60,
    "spiritPower": 4,
    "ammoFlat": 0,
    "ammoPercentage": 0.15,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 81,
    "name": "Extra Charge",
    "tier": "T1",
    "type": "Spirit",
    "bulletPower": 0.06,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 4,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 82,
    "name": "Extra Spirit",
    "tier": "T1",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 35,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 1,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 83,
    "name": "Mystic Burst",
    "tier": "T1",
    "type": "Spirit",
    "bulletPower": 0.06,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 4,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 40,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 84,
    "name": "Mystic Reach",
    "tier": "T1",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 4,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.05,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 85,
    "name": "Spirit Strike",
    "tier": "T1",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 4,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0.15,
    "healthRegen": 1,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 100,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": -0.12,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 86,
    "name": "Infuser",
    "tier": "T1",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 50,
    "spiritPower": 20,
    "ammoFlat": 0,
    "ammoPercentage": 0.1,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0.2,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 87,
    "name": "Bullet Resist Shredder",
    "tier": "T2",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 100,
    "spiritPower": 8,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.05,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": -0.12,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 88,
    "name": "Duration Extender",
    "tier": "T2",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 100,
    "spiritPower": 8,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 1.75,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 89,
    "name": "Improved Cooldown",
    "tier": "T2",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 8,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 1.5,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 90,
    "name": "Mystic Vulnerability",
    "tier": "T2",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 8,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.06,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": -0.12,
    "conditional": "Yes",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 91,
    "name": "Quicksilver Reload",
    "tier": "T2",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 8,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.15,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 92,
    "name": "Suppressor",
    "tier": "T2",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 50,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 2.5,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 93,
    "name": "Cold Front",
    "tier": "T2",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 8,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.1,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 94,
    "name": "Decay",
    "tier": "T2",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 15,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 95,
    "name": "Slowing Hex",
    "tier": "T2",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 13,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 1,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 96,
    "name": "Withering Whip",
    "tier": "T2",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 50,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0.08,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": -0.14,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 97,
    "name": "Improved Burst",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0.08,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 100,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 98,
    "name": "Improved Reach",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 18,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.12,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 99,
    "name": "Improved Spirit",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 100,
    "spiritPower": 33,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 3,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 1,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 100,
    "name": "Mystic Slow",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 100,
    "spiritPower": 18,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 3,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 101,
    "name": "Rapid Recharge",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 102,
    "name": "Superior Cooldown",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 4,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 103,
    "name": "Superior Duration",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0.15,
    "vitality": 0,
    "bonusHealth": 175,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 4,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 104,
    "name": "Surge of Power",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 75,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 3,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 105,
    "name": "Torment Pulse",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 125,
    "spiritPower": 18,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 106,
    "name": "Ethereal Shift",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 26,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 107,
    "name": "Knockdown",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 18,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 200,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 108,
    "name": "Silence Glyph",
    "tier": "T3",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 12,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 200,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 1,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 109,
    "name": "Boundless Spirit",
    "tier": "T4",
    "type": "Spirit",
    "bulletPower": 0.25,
    "vitality": 0,
    "bonusHealth": 300,
    "spiritPower": 76,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 15,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 2,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  },
  {
    "id": 110,
    "name": "Diviner's Kevlar",
    "tier": "T4",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 56,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0.2,
    "bulletShieldHealth": 700,
    "spiritShieldHealth": 700,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 111,
    "name": "Escalating Exposure",
    "tier": "T4",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 125,
    "spiritPower": 16,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.15,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 112,
    "name": "Mystic Reverb",
    "tier": "T4",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 16,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0.15,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0.15,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "No",
    "passive": "Yes"
  },
  {
    "id": 113,
    "name": "Curse",
    "tier": "T4",
    "type": "Spirit",
    "bulletPower": 0.2,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 24,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 114,
    "name": "Echo Shard",
    "tier": "T4",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 24,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.16,
    "spiritResist": 0,
    "movementSpeed": 1,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 115,
    "name": "Magic Carpet",
    "tier": "T4",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 150,
    "spiritPower": 31,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 400,
    "spiritShieldHealth": 400,
    "bulletResist": 0,
    "spiritResist": 0,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "Yes",
    "active": "Yes",
    "passive": "No"
  },
  {
    "id": 116,
    "name": "Refresher",
    "tier": "T4",
    "type": "Spirit",
    "bulletPower": 0,
    "vitality": 0,
    "bonusHealth": 0,
    "spiritPower": 16,
    "ammoFlat": 0,
    "ammoPercentage": 0,
    "fireRate": 0,
    "meleeDamage": 0,
    "healthRegen": 0,
    "bulletLifesteal": 0,
    "spiritLifesteal": 0,
    "bulletShieldHealth": 0,
    "spiritShieldHealth": 0,
    "bulletResist": 0.08,
    "spiritResist": 0.16,
    "movementSpeed": 0,
    "sprintSpeed": 0,
    "bulletResistReduction": 0,
    "spiritResistReduction": 0,
    "conditional": "No",
    "active": "No",
    "passive": "No"
  }
];
